const supabase = require('../config/supabase');

const createCategory = async (req, res) => {
  // ✅ SECURE: Get the User ID from the Clerk Token (req.auth)
  // This ensures no one can spoof another user's ID
  const authenticatedUserId = req.auth.userId;

  // We only take the name and id from the body
  const { category_id, category_name } = req.body;
  
  try {
    // Basic validation
    if (!category_name) {
      return res.status(400).json({ error: 'Category name is required' });
    }

    const { data, error } = await supabase
      .from('categories')
      .insert({
        categoryid: category_id,        // The UUID generated by the App
        userid: authenticatedUserId,     // The verified Clerk User ID
        categoryname: category_name,
        sourcecount: 0,
        takeawaycount: 0,
        isdeleted: false,
        createdat: new Date().toISOString(),
        updatedat: new Date().toISOString()
      })
      .select()
      .single();
    
    if (error) {
      console.error('Supabase Error:', error.message);
      throw error;
    }
    
    res.status(201).json({
      message: 'Category created successfully',
      data: data
    });
  } catch (error) {
    console.error('Error creating category:', error);
    res.status(500).json({ error: 'Failed to create category' });
  }
};

module.exports = { createCategory };
